version: '2'
services:
  mongo:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - "3345:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - mongo-storage:/data/db

  staratlas:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - LOG_ORDERBOOK=${LOG_ORDERBOOK}
      - LOG_ORDER=${LOG_ORDER}
      - /etc/localtime:/etc/localtime:ro


volumes:
  mongo-storage:
 