FROM node:lts-alpine3.16 AS base

# Stage_1 BUILD
FROM base AS build
WORKDIR /usr/src/app

COPY package.json .
RUN npm install
COPY . .
RUN npx tsc -p ./tsconfig.json


# Stage_2 PROD
FROM base AS prod
WORKDIR /usr/src/app

COPY package.json .
RUN npm update
RUN npm install --production
COPY --from=build /usr/src/app/build dist

CMD ["node", "/usr/src/app/dist/index.js"]